# Generated by Django 4.2.5 on 2023-09-15 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('starshop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='Author',
        ),
        migrations.AddField(
            model_name='quote',
            name='Author',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='starshop.author'),
        ),
    ]
