# Generated by Django 4.2.5 on 2023-09-15 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('starshop', '0002_remove_quote_author_quote_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(default='null', max_length=300),
        ),
        migrations.AlterField(
            model_name='quote',
            name='Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='starshop.author'),
        ),
    ]
