# Generated by Django 4.2.5 on 2023-09-15 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starshop', '0003_alter_author_name_alter_quote_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
