# Generated by Django 4.2.5 on 2023-09-15 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starshop', '0005_alter_author_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author_slug',
            field=models.CharField(default=1, max_length=200),
        ),
    ]
