# Generated by Django 4.2.5 on 2023-09-15 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starshop', '0006_author_author_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_slug',
            field=models.CharField(max_length=200),
        ),
    ]
