# Generated by Django 4.2.5 on 2023-09-15 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('starshop', '0007_alter_author_author_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='author_slug',
        ),
    ]
