# Generated by Django 4.2.5 on 2023-09-15 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starshop', '0008_remove_author_author_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='Author',
        ),
        migrations.AddField(
            model_name='quote',
            name='Author',
            field=models.ManyToManyField(to='starshop.author'),
        ),
    ]
